# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-18 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0003_auto_20170419_1546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['title'], 'verbose_name': '\u041c\u0435\u0441\u0442\u043e', 'verbose_name_plural': '\u041c\u0435\u0441\u0442\u0430'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['title'], 'verbose_name': '\u0421\u043f\u043e\u0440\u0442', 'verbose_name_plural': '\u0421\u043f\u043e\u0440\u0442'},
        ),
        migrations.AlterModelOptions(
            name='tourney',
            options={'ordering': ['date_start'], 'verbose_name': '\u0421\u043e\u0440\u0435\u0432\u043d\u043e\u0432\u0430\u043d\u0438\u0435', 'verbose_name_plural': '\u0421\u043e\u0440\u0435\u0432\u043d\u043e\u0432\u0430\u043d\u0438\u044f'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['fio'], 'verbose_name': '\u0420\u0430\u0431\u043e\u0442\u043d\u0438\u043a', 'verbose_name_plural': '\u0420\u0430\u0431\u043e\u0442\u043d\u0438\u043a\u0438'},
        ),
        migrations.AddField(
            model_name='tourney',
            name='typer',
            field=models.CharField(choices=[(b'1', b'\xd0\x9c\xd0\xb8\xd0\xbd\xd1\x81\xd0\xbf\xd0\xbe\xd1\x80\xd1\x82'), (b'2', b'\xd0\x92\xd1\x8b\xd0\xb5\xd0\xb7\xd0\xb4'), (b'3', b'\xd0\x94\xd1\x80\xd1\x83\xd0\xb3\xd0\xbe\xd0\xb5')], default=1, max_length=25),
        ),
    ]
