# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-19 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0004_auto_20171018_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='arenda_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name=b'\xd0\x90\xd1\x80\xd0\xb5\xd0\xbd\xd0\xb4\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='bus_on',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\xa4\xd1\x80\xd0\xb0\xd1\x85\xd1\x82\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5 \xd0\xb0\xd0\xb2\xd1\x82\xd0\xbe\xd0\xb1\xd1\x83\xd1\x81\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='location2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourneys2', to='sportapp.Location', verbose_name=b'\xd0\x9c\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe2'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='location3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourneys3', to='sportapp.Location', verbose_name=b'\xd0\x9c\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe3'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='location4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourneys4', to='sportapp.Location', verbose_name=b'\xd0\x9c\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe4'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='medic_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name=b'\xd0\x9c\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xba\xd0\xb8'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='pitanie_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name=b'\xd0\x9f\xd0\xb8\xd1\x82\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='proezd_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name=b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xb5\xd0\xb7\xd0\xb4 (\xd0\xb1\xd0\xb8\xd0\xbb\xd0\xb5\xd1\x82\xd1\x8b)'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='projiv_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name=b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xb6\xd0\xb8\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb5'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='vznos_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name=b'\xd0\x97\xd0\xb0\xd1\x8f\xd0\xb2\xd0\xbe\xd1\x87\xd0\xbd\xd1\x8b\xd0\xb9 \xd0\xb2\xd0\xb7\xd0\xbd\xd0\xbe\xd1\x81'),
        ),
    ]
