# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0006_tourney_transport_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='typer',
            field=models.CharField(choices=[(b'USS', b'\xd0\xa3\xd0\xa1\xd0\xa1'), (b'RME', b'\xd0\xa0\xd0\xb0\xd0\xb9\xd0\xbe\xd0\xbd'), (b'RU', b'\xd0\x94\xd1\x80\xd1\x83\xd0\xb3\xd0\xbe\xd0\xb9 \xd1\x80\xd0\xb5\xd0\xb3\xd0\xb8\xd0\xbe\xd0\xbd'), (b'NO', b'\xd0\x9d\xd0\xb5 \xd1\x83\xd1\x81\xd1\x82\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xbe')], default=b'NO', max_length=5),
        ),
    ]
