# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-15 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0008_auto_20171115_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='is_uss',
            field=models.BooleanField(default=True, verbose_name=b'\xd0\x9d\xd0\xb0 \xd0\xb1\xd0\xb0\xd0\xb7\xd0\xb5 \xd0\xa3\xd0\xa1\xd0\xa1'),
        ),
    ]
