# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0009_tourney_is_uss'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='ambulance_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbe\xd1\x80\xd0\xb0\xd1\x8f \xd0\xbf\xd0\xbe\xd0\xbc\xd0\xbe\xd1\x89\xd1\x8c(\xd1\x81\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0)'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='ambulance_time',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd0\xba\xd0\xbe\xd1\x80\xd0\xb0\xd1\x8f \xd0\xbf\xd0\xbe\xd0\xbc\xd0\xbe\xd1\x89\xd1\x8c(\xd1\x87\xd0\xb0\xd1\x81\xd1\x8b)'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='badges_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xb1\xd0\xb5\xd0\xb9\xd0\xb4\xd0\xb6\xd0\xb5\xd0\xb9'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='badges_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xb1\xd0\xb5\xd0\xb9\xd0\xb4\xd0\xb6\xd0\xb5\xd0\xb9'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='banners_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xb1\xd0\xb0\xd0\xbd\xd0\xbd\xd0\xb5\xd1\x80\xd0\xbe\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='banners_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xb1\xd0\xb0\xd0\xbd\xd0\xbd\xd0\xb5\xd1\x80\xd0\xbe\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='cup1_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xba\xd1\x83\xd0\xb1\xd0\xba\xd0\xbe\xd0\xb2 \xd0\xb7\xd0\xb0 1 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='cup1_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xba\xd1\x83\xd0\xb1\xd0\xba\xd0\xbe\xd0\xb2 \xd0\xb7\xd0\xb0 1 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='cup2_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xba\xd1\x83\xd0\xb1\xd0\xba\xd0\xbe\xd0\xb2 \xd0\xb7\xd0\xb0 2 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='cup2_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xba\xd1\x83\xd0\xb1\xd0\xba\xd0\xbe\xd0\xb2 \xd0\xb7\xd0\xb0 2 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='cup3_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xba\xd1\x83\xd0\xb1\xd0\xba\xd0\xbe\xd0\xb2 \xd0\xb7\xd0\xb0 3 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='cup3_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xba\xd1\x83\xd0\xb1\xd0\xba\xd0\xbe\xd0\xb2 \xd0\xb7\xd0\xb0 3 \xd0\xbc\xd0\xb5\xd1\x81\xd1\x82\xd0\xbe'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='cups_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xba\xd1\x83\xd0\xb1\xd0\xba\xd0\xbe\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='cups_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xba\xd1\x83\xd0\xb1\xd0\xba\xd0\xbe\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='diploms_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xb4\xd0\xb8\xd0\xbf\xd0\xbb\xd0\xbe\xd0\xbc\xd0\xbe\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='diploms_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xb4\xd0\xb8\xd0\xbf\xd0\xbb\xd0\xbe\xd0\xbc\xd0\xbe\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='frames_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd1\x80\xd0\xb0\xd0\xbc\xd0\xbe\xd0\xba'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='frames_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd1\x80\xd0\xb0\xd0\xbc\xd0\xbe\xd0\xba'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='medals_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb0\xd0\xbb\xd0\xb5\xd0\xb9'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='medals_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xbc\xd0\xb5\xd0\xb4\xd0\xb0\xd0\xbb\xd0\xb5\xd0\xb9'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='numbers_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80\xd0\xbe\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='numbers_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xbd\xd0\xbe\xd0\xbc\xd0\xb5\xd1\x80\xd0\xbe\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='postersA2_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xb0\xd1\x84\xd0\xb8\xd1\x88 \xd0\x902'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='postersA2_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xb0\xd1\x84\xd0\xb8\xd1\x88 \xd0\x902'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='postersA3_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xb0\xd1\x84\xd0\xb8\xd1\x88 \xd0\x903'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='postersA3_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xb0\xd1\x84\xd0\xb8\xd1\x88 \xd0\x903'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='postersA4_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xb0\xd1\x84\xd0\xb8\xd1\x88 \xd0\x904'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='postersA4_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xb0\xd1\x84\xd0\xb8\xd1\x88 \xd0\x904'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='prizes_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xbf\xd1\x80\xd0\xb8\xd0\xb7\xd0\xbe\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='prizes_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xbf\xd1\x80\xd0\xb8\xd0\xb7\xd0\xbe\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='protocol',
            field=models.BooleanField(default=0, verbose_name=b'\xd0\x9f\xd1\x80\xd0\xbe\xd1\x82\xd0\xbe\xd0\xba\xd0\xbe\xd0\xbb'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='report',
            field=models.BooleanField(default=0, verbose_name=b'\xd0\x9e\xd1\x82\xd1\x87\xd0\xb5\xd1\x82'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='stickers_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xbd\xd0\xb0\xd0\xba\xd0\xbb\xd0\xb5\xd0\xb5\xd0\xba'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='stickers_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xbd\xd0\xb0\xd0\xba\xd0\xbb\xd0\xb5\xd0\xb5\xd0\xba'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='tablesA1_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd1\x82\xd0\xb0\xd0\xb1\xd0\xbb\xd0\xb8\xd1\x86 \xd0\x901'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='tablesA1_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd1\x82\xd0\xb0\xd0\xb1\xd0\xbb\xd0\xb8\xd1\x86 \xd0\x901'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='tokens_kol',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbb-\xd0\xb2\xd0\xbe \xd0\xb6\xd0\xb5\xd1\x82\xd0\xbe\xd0\xbd\xd0\xbe\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='tokens_sum',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xbc\xd0\xbc\xd0\xb0 \xd0\xb6\xd0\xb5\xd1\x82\xd0\xbe\xd0\xbd\xd0\xbe\xd0\xb2'),
        ),
    ]
