# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportapp', '0012_tourney_other_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourney',
            name='judje_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True, verbose_name=b'\xd0\xa1\xd1\x83\xd0\xb4\xd0\xb5\xd0\xb9\xd1\x81\xd0\xba\xd0\xb8\xd0\xb5'),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='medic_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True, verbose_name=b'\xd0\x9c\xd0\xb5\xd0\xb4\xd0\xb8\xd0\xba\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='participants',
            field=models.IntegerField(default=10, null=True, verbose_name=b'\xd0\xa3\xd1\x87\xd0\xb0\xd1\x81\xd1\x82\xd0\xbd\xd0\xb8\xd0\xba\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='print_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True, verbose_name=b'\xd0\x9f\xd0\xb5\xd1\x87\xd0\xb0\xd1\x82\xd0\xbd\xd0\xb0\xd1\x8f'),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='reward_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, null=True, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb3\xd1\x80\xd0\xb0\xd0\xb4\xd0\xbd\xd0\xb0\xd1\x8f'),
        ),
    ]
